/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as TournamentRouteImport } from './routes/tournament'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RoomRouteImport } from './routes/room'
import { Route as PuzzlesRouteImport } from './routes/puzzles'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as PlayRouteImport } from './routes/play'
import { Route as OpeningsRouteImport } from './routes/openings'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ClubsRouteImport } from './routes/clubs'
import { Route as ClubRouteImport } from './routes/club'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomIndexRouteImport } from './routes/room.index'
import { Route as PuzzlesIndexRouteImport } from './routes/puzzles.index'
import { Route as PlayIndexRouteImport } from './routes/play.index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as CourseIndexRouteImport } from './routes/course.index'
import { Route as RoomRoomIdRouteImport } from './routes/room.$roomId'
import { Route as PuzzlesRushRouteImport } from './routes/puzzles.rush'
import { Route as PlayLocalRouteImport } from './routes/play.local'
import { Route as PlayHistoryRouteImport } from './routes/play.history'
import { Route as PlayFriendRouteImport } from './routes/play.friend'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as GameIdRouteImport } from './routes/game.$id'
import { Route as CourseSlugRouteImport } from './routes/course.$slug'
import { Route as GameIdReviewRouteImport } from './routes/game.$id.review'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentRoute = TournamentRouteImport.update({
  id: '/tournament',
  path: '/tournament',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoute = RoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesRoute = PuzzlesRouteImport.update({
  id: '/puzzles',
  path: '/puzzles',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const OpeningsRoute = OpeningsRouteImport.update({
  id: '/openings',
  path: '/openings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsRoute = ClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomIndexRoute = RoomIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoomRoute,
} as any)
const PuzzlesIndexRoute = PuzzlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PuzzlesRoute,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayRoute,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRoute,
} as any)
const CourseIndexRoute = CourseIndexRouteImport.update({
  id: '/course/',
  path: '/course/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => RoomRoute,
} as any)
const PuzzlesRushRoute = PuzzlesRushRouteImport.update({
  id: '/rush',
  path: '/rush',
  getParentRoute: () => PuzzlesRoute,
} as any)
const PlayLocalRoute = PlayLocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => PlayRoute,
} as any)
const PlayHistoryRoute = PlayHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PlayRoute,
} as any)
const PlayFriendRoute = PlayFriendRouteImport.update({
  id: '/friend',
  path: '/friend',
  getParentRoute: () => PlayRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const GameIdRoute = GameIdRouteImport.update({
  id: '/game/$id',
  path: '/game/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseSlugRoute = CourseSlugRouteImport.update({
  id: '/course/$slug',
  path: '/course/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIdReviewRoute = GameIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => GameIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/auth': typeof AuthRoute
  '/club': typeof ClubRoute
  '/clubs': typeof ClubsRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/friends': typeof FriendsRoute
  '/home': typeof HomeRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/openings': typeof OpeningsRoute
  '/play': typeof PlayRouteWithChildren
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/puzzles': typeof PuzzlesRouteWithChildren
  '/room': typeof RoomRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tournament': typeof TournamentRoute
  '/tournaments': typeof TournamentsRoute
  '/wallet': typeof WalletRoute
  '/course/$slug': typeof CourseSlugRoute
  '/game/$id': typeof GameIdRouteWithChildren
  '/news/$slug': typeof NewsSlugRoute
  '/play/friend': typeof PlayFriendRoute
  '/play/history': typeof PlayHistoryRoute
  '/play/local': typeof PlayLocalRoute
  '/puzzles/rush': typeof PuzzlesRushRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/course/': typeof CourseIndexRoute
  '/news/': typeof NewsIndexRoute
  '/play/': typeof PlayIndexRoute
  '/puzzles/': typeof PuzzlesIndexRoute
  '/room/': typeof RoomIndexRoute
  '/game/$id/review': typeof GameIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/auth': typeof AuthRoute
  '/club': typeof ClubRoute
  '/clubs': typeof ClubsRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/friends': typeof FriendsRoute
  '/home': typeof HomeRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/openings': typeof OpeningsRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tournament': typeof TournamentRoute
  '/tournaments': typeof TournamentsRoute
  '/wallet': typeof WalletRoute
  '/course/$slug': typeof CourseSlugRoute
  '/game/$id': typeof GameIdRouteWithChildren
  '/news/$slug': typeof NewsSlugRoute
  '/play/friend': typeof PlayFriendRoute
  '/play/history': typeof PlayHistoryRoute
  '/play/local': typeof PlayLocalRoute
  '/puzzles/rush': typeof PuzzlesRushRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/course': typeof CourseIndexRoute
  '/news': typeof NewsIndexRoute
  '/play': typeof PlayIndexRoute
  '/puzzles': typeof PuzzlesIndexRoute
  '/room': typeof RoomIndexRoute
  '/game/$id/review': typeof GameIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/auth': typeof AuthRoute
  '/club': typeof ClubRoute
  '/clubs': typeof ClubsRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/friends': typeof FriendsRoute
  '/home': typeof HomeRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/openings': typeof OpeningsRoute
  '/play': typeof PlayRouteWithChildren
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/puzzles': typeof PuzzlesRouteWithChildren
  '/room': typeof RoomRouteWithChildren
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tournament': typeof TournamentRoute
  '/tournaments': typeof TournamentsRoute
  '/wallet': typeof WalletRoute
  '/course/$slug': typeof CourseSlugRoute
  '/game/$id': typeof GameIdRouteWithChildren
  '/news/$slug': typeof NewsSlugRoute
  '/play/friend': typeof PlayFriendRoute
  '/play/history': typeof PlayHistoryRoute
  '/play/local': typeof PlayLocalRoute
  '/puzzles/rush': typeof PuzzlesRushRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/course/': typeof CourseIndexRoute
  '/news/': typeof NewsIndexRoute
  '/play/': typeof PlayIndexRoute
  '/puzzles/': typeof PuzzlesIndexRoute
  '/room/': typeof RoomIndexRoute
  '/game/$id/review': typeof GameIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/auth'
    | '/club'
    | '/clubs'
    | '/community'
    | '/dashboard'
    | '/friends'
    | '/home'
    | '/leaderboards'
    | '/learn'
    | '/login'
    | '/news'
    | '/notifications'
    | '/openings'
    | '/play'
    | '/premium'
    | '/profile'
    | '/puzzles'
    | '/room'
    | '/search'
    | '/settings'
    | '/signup'
    | '/tournament'
    | '/tournaments'
    | '/wallet'
    | '/course/$slug'
    | '/game/$id'
    | '/news/$slug'
    | '/play/friend'
    | '/play/history'
    | '/play/local'
    | '/puzzles/rush'
    | '/room/$roomId'
    | '/course/'
    | '/news/'
    | '/play/'
    | '/puzzles/'
    | '/room/'
    | '/game/$id/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/auth'
    | '/club'
    | '/clubs'
    | '/community'
    | '/dashboard'
    | '/friends'
    | '/home'
    | '/leaderboards'
    | '/learn'
    | '/login'
    | '/notifications'
    | '/openings'
    | '/premium'
    | '/profile'
    | '/search'
    | '/settings'
    | '/signup'
    | '/tournament'
    | '/tournaments'
    | '/wallet'
    | '/course/$slug'
    | '/game/$id'
    | '/news/$slug'
    | '/play/friend'
    | '/play/history'
    | '/play/local'
    | '/puzzles/rush'
    | '/room/$roomId'
    | '/course'
    | '/news'
    | '/play'
    | '/puzzles'
    | '/room'
    | '/game/$id/review'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/auth'
    | '/club'
    | '/clubs'
    | '/community'
    | '/dashboard'
    | '/friends'
    | '/home'
    | '/leaderboards'
    | '/learn'
    | '/login'
    | '/news'
    | '/notifications'
    | '/openings'
    | '/play'
    | '/premium'
    | '/profile'
    | '/puzzles'
    | '/room'
    | '/search'
    | '/settings'
    | '/signup'
    | '/tournament'
    | '/tournaments'
    | '/wallet'
    | '/course/$slug'
    | '/game/$id'
    | '/news/$slug'
    | '/play/friend'
    | '/play/history'
    | '/play/local'
    | '/puzzles/rush'
    | '/room/$roomId'
    | '/course/'
    | '/news/'
    | '/play/'
    | '/puzzles/'
    | '/room/'
    | '/game/$id/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  AuthRoute: typeof AuthRoute
  ClubRoute: typeof ClubRoute
  ClubsRoute: typeof ClubsRoute
  CommunityRoute: typeof CommunityRoute
  DashboardRoute: typeof DashboardRoute
  FriendsRoute: typeof FriendsRoute
  HomeRoute: typeof HomeRoute
  LeaderboardsRoute: typeof LeaderboardsRoute
  LearnRoute: typeof LearnRoute
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  OpeningsRoute: typeof OpeningsRoute
  PlayRoute: typeof PlayRouteWithChildren
  PremiumRoute: typeof PremiumRoute
  ProfileRoute: typeof ProfileRoute
  PuzzlesRoute: typeof PuzzlesRouteWithChildren
  RoomRoute: typeof RoomRouteWithChildren
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TournamentRoute: typeof TournamentRoute
  TournamentsRoute: typeof TournamentsRoute
  WalletRoute: typeof WalletRoute
  CourseSlugRoute: typeof CourseSlugRoute
  GameIdRoute: typeof GameIdRouteWithChildren
  CourseIndexRoute: typeof CourseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament': {
      id: '/tournament'
      path: '/tournament'
      fullPath: '/tournament'
      preLoaderRoute: typeof TournamentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room': {
      id: '/room'
      path: '/room'
      fullPath: '/room'
      preLoaderRoute: typeof RoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles': {
      id: '/puzzles'
      path: '/puzzles'
      fullPath: '/puzzles'
      preLoaderRoute: typeof PuzzlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openings': {
      id: '/openings'
      path: '/openings'
      fullPath: '/openings'
      preLoaderRoute: typeof OpeningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs': {
      id: '/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof ClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/': {
      id: '/room/'
      path: '/'
      fullPath: '/room/'
      preLoaderRoute: typeof RoomIndexRouteImport
      parentRoute: typeof RoomRoute
    }
    '/puzzles/': {
      id: '/puzzles/'
      path: '/'
      fullPath: '/puzzles/'
      preLoaderRoute: typeof PuzzlesIndexRouteImport
      parentRoute: typeof PuzzlesRoute
    }
    '/play/': {
      id: '/play/'
      path: '/'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof PlayRoute
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRoute
    }
    '/course/': {
      id: '/course/'
      path: '/course'
      fullPath: '/course/'
      preLoaderRoute: typeof CourseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof RoomRoute
    }
    '/puzzles/rush': {
      id: '/puzzles/rush'
      path: '/rush'
      fullPath: '/puzzles/rush'
      preLoaderRoute: typeof PuzzlesRushRouteImport
      parentRoute: typeof PuzzlesRoute
    }
    '/play/local': {
      id: '/play/local'
      path: '/local'
      fullPath: '/play/local'
      preLoaderRoute: typeof PlayLocalRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/history': {
      id: '/play/history'
      path: '/history'
      fullPath: '/play/history'
      preLoaderRoute: typeof PlayHistoryRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/friend': {
      id: '/play/friend'
      path: '/friend'
      fullPath: '/play/friend'
      preLoaderRoute: typeof PlayFriendRouteImport
      parentRoute: typeof PlayRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/game/$id': {
      id: '/game/$id'
      path: '/game/$id'
      fullPath: '/game/$id'
      preLoaderRoute: typeof GameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$slug': {
      id: '/course/$slug'
      path: '/course/$slug'
      fullPath: '/course/$slug'
      preLoaderRoute: typeof CourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$id/review': {
      id: '/game/$id/review'
      path: '/review'
      fullPath: '/game/$id/review'
      preLoaderRoute: typeof GameIdReviewRouteImport
      parentRoute: typeof GameIdRoute
    }
  }
}

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface PlayRouteChildren {
  PlayFriendRoute: typeof PlayFriendRoute
  PlayHistoryRoute: typeof PlayHistoryRoute
  PlayLocalRoute: typeof PlayLocalRoute
  PlayIndexRoute: typeof PlayIndexRoute
}

const PlayRouteChildren: PlayRouteChildren = {
  PlayFriendRoute: PlayFriendRoute,
  PlayHistoryRoute: PlayHistoryRoute,
  PlayLocalRoute: PlayLocalRoute,
  PlayIndexRoute: PlayIndexRoute,
}

const PlayRouteWithChildren = PlayRoute._addFileChildren(PlayRouteChildren)

interface PuzzlesRouteChildren {
  PuzzlesRushRoute: typeof PuzzlesRushRoute
  PuzzlesIndexRoute: typeof PuzzlesIndexRoute
}

const PuzzlesRouteChildren: PuzzlesRouteChildren = {
  PuzzlesRushRoute: PuzzlesRushRoute,
  PuzzlesIndexRoute: PuzzlesIndexRoute,
}

const PuzzlesRouteWithChildren =
  PuzzlesRoute._addFileChildren(PuzzlesRouteChildren)

interface RoomRouteChildren {
  RoomRoomIdRoute: typeof RoomRoomIdRoute
  RoomIndexRoute: typeof RoomIndexRoute
}

const RoomRouteChildren: RoomRouteChildren = {
  RoomRoomIdRoute: RoomRoomIdRoute,
  RoomIndexRoute: RoomIndexRoute,
}

const RoomRouteWithChildren = RoomRoute._addFileChildren(RoomRouteChildren)

interface GameIdRouteChildren {
  GameIdReviewRoute: typeof GameIdReviewRoute
}

const GameIdRouteChildren: GameIdRouteChildren = {
  GameIdReviewRoute: GameIdReviewRoute,
}

const GameIdRouteWithChildren =
  GameIdRoute._addFileChildren(GameIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  AuthRoute: AuthRoute,
  ClubRoute: ClubRoute,
  ClubsRoute: ClubsRoute,
  CommunityRoute: CommunityRoute,
  DashboardRoute: DashboardRoute,
  FriendsRoute: FriendsRoute,
  HomeRoute: HomeRoute,
  LeaderboardsRoute: LeaderboardsRoute,
  LearnRoute: LearnRoute,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  OpeningsRoute: OpeningsRoute,
  PlayRoute: PlayRouteWithChildren,
  PremiumRoute: PremiumRoute,
  ProfileRoute: ProfileRoute,
  PuzzlesRoute: PuzzlesRouteWithChildren,
  RoomRoute: RoomRouteWithChildren,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TournamentRoute: TournamentRoute,
  TournamentsRoute: TournamentsRoute,
  WalletRoute: WalletRoute,
  CourseSlugRoute: CourseSlugRoute,
  GameIdRoute: GameIdRouteWithChildren,
  CourseIndexRoute: CourseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
