/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawalPolicyRouteImport } from './routes/withdrawal-policy'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VerifyResetOtpRouteImport } from './routes/verify-reset-otp'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as TournamentRouteImport } from './routes/tournament'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SeasonsRouteImport } from './routes/seasons'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RoomRouteImport } from './routes/room'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as PuzzlesRouteImport } from './routes/puzzles'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as PlayRouteImport } from './routes/play'
import { Route as OpeningsRouteImport } from './routes/openings'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GrievancePolicyRouteImport } from './routes/grievance-policy'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FairPlayPolicyRouteImport } from './routes/fair-play-policy'
import { Route as FairPlayAntiCheatingPolicyRouteImport } from './routes/fair-play-anti-cheating-policy'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EditorialTeamRouteImport } from './routes/editorial-team'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreatePasswordRouteImport } from './routes/create-password'
import { Route as ContactGrievancePolicyRouteImport } from './routes/contact-grievance-policy'
import { Route as CommunityPolicyRouteImport } from './routes/community-policy'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ClubsRouteImport } from './routes/clubs'
import { Route as ClanRouteImport } from './routes/clan'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AboutChessRouteImport } from './routes/about-chess'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchIndexRouteImport } from './routes/watch.index'
import { Route as RoomIndexRouteImport } from './routes/room.index'
import { Route as PuzzlesIndexRouteImport } from './routes/puzzles.index'
import { Route as PlayIndexRouteImport } from './routes/play.index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as CourseIndexRouteImport } from './routes/course.index'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as ClansIndexRouteImport } from './routes/clans.index'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WatchIdRouteImport } from './routes/watch.$id'
import { Route as WalletBankRouteImport } from './routes/wallet.bank'
import { Route as VerifyEmailTokenRouteImport } from './routes/verify-email.$token'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as TournamentIdRouteImport } from './routes/tournament.$id'
import { Route as RoomRoomIdRouteImport } from './routes/room.$roomId'
import { Route as PuzzlesRushRouteImport } from './routes/puzzles.rush'
import { Route as PlayLocalRouteImport } from './routes/play.local'
import { Route as PlayHistoryRouteImport } from './routes/play.history'
import { Route as PlayFriendRouteImport } from './routes/play.friend'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as GameIdRouteImport } from './routes/game.$id'
import { Route as FriendsActivityRouteImport } from './routes/friends_.activity'
import { Route as CourseSlugRouteImport } from './routes/course.$slug'
import { Route as CommunityExploreRouteImport } from './routes/community.explore'
import { Route as CommunityBookmarksRouteImport } from './routes/community.bookmarks'
import { Route as ClanSlugRouteImport } from './routes/clan.$slug'
import { Route as ChatGlobalRouteImport } from './routes/chat.global'
import { Route as ChatDiscoverRouteImport } from './routes/chat.discover'
import { Route as ArenaIdRouteImport } from './routes/arena.$id'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin.withdrawals'
import { Route as AdminWalletRouteImport } from './routes/admin.wallet'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTrRouteImport } from './routes/admin.tr'
import { Route as AdminTournamentsRouteImport } from './routes/admin.tournaments'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSeasonsRouteImport } from './routes/admin.seasons'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminRankingRouteImport } from './routes/admin.ranking'
import { Route as AdminPuzzlesRouteImport } from './routes/admin.puzzles'
import { Route as AdminPremiumRouteImport } from './routes/admin.premium'
import { Route as AdminPoliciesRouteImport } from './routes/admin.policies'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminKycRouteImport } from './routes/admin.kyc'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as AdminCommunityRouteImport } from './routes/admin.community'
import { Route as AdminClansRouteImport } from './routes/admin.clans'
import { Route as AdminChatRouteImport } from './routes/admin.chat'
import { Route as AdminAnticheatRouteImport } from './routes/admin.anticheat'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAboutChessRouteImport } from './routes/admin.about-chess'
import { Route as GameIdReviewRouteImport } from './routes/game.$id.review'
import { Route as CommunityPostIdRouteImport } from './routes/community.post.$id'
import { Route as ChatRoomSlugRouteImport } from './routes/chat.room.$slug'
import { Route as ChatDmUsernameRouteImport } from './routes/chat.dm.$username'

const WithdrawalPolicyRoute = WithdrawalPolicyRouteImport.update({
  id: '/withdrawal-policy',
  path: '/withdrawal-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyResetOtpRoute = VerifyResetOtpRouteImport.update({
  id: '/verify-reset-otp',
  path: '/verify-reset-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentRoute = TournamentRouteImport.update({
  id: '/tournament',
  path: '/tournament',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonsRoute = SeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoute = RoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesRoute = PuzzlesRouteImport.update({
  id: '/puzzles',
  path: '/puzzles',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const OpeningsRoute = OpeningsRouteImport.update({
  id: '/openings',
  path: '/openings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GrievancePolicyRoute = GrievancePolicyRouteImport.update({
  id: '/grievance-policy',
  path: '/grievance-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FairPlayPolicyRoute = FairPlayPolicyRouteImport.update({
  id: '/fair-play-policy',
  path: '/fair-play-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const FairPlayAntiCheatingPolicyRoute =
  FairPlayAntiCheatingPolicyRouteImport.update({
    id: '/fair-play-anti-cheating-policy',
    path: '/fair-play-anti-cheating-policy',
    getParentRoute: () => rootRouteImport,
  } as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialTeamRoute = EditorialTeamRouteImport.update({
  id: '/editorial-team',
  path: '/editorial-team',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatePasswordRoute = CreatePasswordRouteImport.update({
  id: '/create-password',
  path: '/create-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactGrievancePolicyRoute = ContactGrievancePolicyRouteImport.update({
  id: '/contact-grievance-policy',
  path: '/contact-grievance-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityPolicyRoute = CommunityPolicyRouteImport.update({
  id: '/community-policy',
  path: '/community-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsRoute = ClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const ClanRoute = ClanRouteImport.update({
  id: '/clan',
  path: '/clan',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutChessRoute = AboutChessRouteImport.update({
  id: '/about-chess',
  path: '/about-chess',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIndexRoute = WatchIndexRouteImport.update({
  id: '/watch/',
  path: '/watch/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomIndexRoute = RoomIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoomRoute,
} as any)
const PuzzlesIndexRoute = PuzzlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PuzzlesRoute,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlayRoute,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NewsRoute,
} as any)
const CourseIndexRoute = CourseIndexRouteImport.update({
  id: '/course/',
  path: '/course/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunityRoute,
} as any)
const ClansIndexRoute = ClansIndexRouteImport.update({
  id: '/clans/',
  path: '/clans/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletBankRoute = WalletBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => WalletRoute,
} as any)
const VerifyEmailTokenRoute = VerifyEmailTokenRouteImport.update({
  id: '/verify-email/$token',
  path: '/verify-email/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentIdRoute = TournamentIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TournamentRoute,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => RoomRoute,
} as any)
const PuzzlesRushRoute = PuzzlesRushRouteImport.update({
  id: '/rush',
  path: '/rush',
  getParentRoute: () => PuzzlesRoute,
} as any)
const PlayLocalRoute = PlayLocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => PlayRoute,
} as any)
const PlayHistoryRoute = PlayHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PlayRoute,
} as any)
const PlayFriendRoute = PlayFriendRouteImport.update({
  id: '/friend',
  path: '/friend',
  getParentRoute: () => PlayRoute,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NewsRoute,
} as any)
const GameIdRoute = GameIdRouteImport.update({
  id: '/game/$id',
  path: '/game/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsActivityRoute = FriendsActivityRouteImport.update({
  id: '/friends_/activity',
  path: '/friends/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseSlugRoute = CourseSlugRouteImport.update({
  id: '/course/$slug',
  path: '/course/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityExploreRoute = CommunityExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityBookmarksRoute = CommunityBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => CommunityRoute,
} as any)
const ClanSlugRoute = ClanSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ClanRoute,
} as any)
const ChatGlobalRoute = ChatGlobalRouteImport.update({
  id: '/global',
  path: '/global',
  getParentRoute: () => ChatRoute,
} as any)
const ChatDiscoverRoute = ChatDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => ChatRoute,
} as any)
const ArenaIdRoute = ArenaIdRouteImport.update({
  id: '/arena/$id',
  path: '/arena/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/admin/withdrawals',
  path: '/admin/withdrawals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWalletRoute = AdminWalletRouteImport.update({
  id: '/admin/wallet',
  path: '/admin/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrRoute = AdminTrRouteImport.update({
  id: '/admin/tr',
  path: '/admin/tr',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTournamentsRoute = AdminTournamentsRouteImport.update({
  id: '/admin/tournaments',
  path: '/admin/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeasonsRoute = AdminSeasonsRouteImport.update({
  id: '/admin/seasons',
  path: '/admin/seasons',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRankingRoute = AdminRankingRouteImport.update({
  id: '/admin/ranking',
  path: '/admin/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPuzzlesRoute = AdminPuzzlesRouteImport.update({
  id: '/admin/puzzles',
  path: '/admin/puzzles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPremiumRoute = AdminPremiumRouteImport.update({
  id: '/admin/premium',
  path: '/admin/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPoliciesRoute = AdminPoliciesRouteImport.update({
  id: '/admin/policies',
  path: '/admin/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/admin/kyc',
  path: '/admin/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/admin/feedback',
  path: '/admin/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommunityRoute = AdminCommunityRouteImport.update({
  id: '/admin/community',
  path: '/admin/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClansRoute = AdminClansRouteImport.update({
  id: '/admin/clans',
  path: '/admin/clans',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/admin/chat',
  path: '/admin/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnticheatRoute = AdminAnticheatRouteImport.update({
  id: '/admin/anticheat',
  path: '/admin/anticheat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAboutChessRoute = AdminAboutChessRouteImport.update({
  id: '/admin/about-chess',
  path: '/admin/about-chess',
  getParentRoute: () => rootRouteImport,
} as any)
const GameIdReviewRoute = GameIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => GameIdRoute,
} as any)
const CommunityPostIdRoute = CommunityPostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => CommunityRoute,
} as any)
const ChatRoomSlugRoute = ChatRoomSlugRouteImport.update({
  id: '/room/$slug',
  path: '/room/$slug',
  getParentRoute: () => ChatRoute,
} as any)
const ChatDmUsernameRoute = ChatDmUsernameRouteImport.update({
  id: '/dm/$username',
  path: '/dm/$username',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-chess': typeof AboutChessRoute
  '/analysis': typeof AnalysisRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRouteWithChildren
  '/clan': typeof ClanRouteWithChildren
  '/clubs': typeof ClubsRoute
  '/community': typeof CommunityRouteWithChildren
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/community-policy': typeof CommunityPolicyRoute
  '/contact-grievance-policy': typeof ContactGrievancePolicyRoute
  '/create-password': typeof CreatePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/editorial-team': typeof EditorialTeamRoute
  '/events': typeof EventsRoute
  '/fair-play-anti-cheating-policy': typeof FairPlayAntiCheatingPolicyRoute
  '/fair-play-policy': typeof FairPlayPolicyRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/friends': typeof FriendsRoute
  '/grievance-policy': typeof GrievancePolicyRoute
  '/home': typeof HomeRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/openings': typeof OpeningsRoute
  '/play': typeof PlayRouteWithChildren
  '/policies': typeof PoliciesRoute
  '/premium': typeof PremiumRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/puzzles': typeof PuzzlesRouteWithChildren
  '/rankings': typeof RankingsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/report': typeof ReportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/room': typeof RoomRouteWithChildren
  '/search': typeof SearchRoute
  '/seasons': typeof SeasonsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/tournament': typeof TournamentRouteWithChildren
  '/tournaments': typeof TournamentsRoute
  '/verify-reset-otp': typeof VerifyResetOtpRoute
  '/wallet': typeof WalletRouteWithChildren
  '/withdrawal-policy': typeof WithdrawalPolicyRoute
  '/admin/about-chess': typeof AdminAboutChessRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/anticheat': typeof AdminAnticheatRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/clans': typeof AdminClansRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/premium': typeof AdminPremiumRoute
  '/admin/puzzles': typeof AdminPuzzlesRoute
  '/admin/ranking': typeof AdminRankingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/seasons': typeof AdminSeasonsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/admin/tr': typeof AdminTrRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/arena/$id': typeof ArenaIdRoute
  '/chat/discover': typeof ChatDiscoverRoute
  '/chat/global': typeof ChatGlobalRoute
  '/clan/$slug': typeof ClanSlugRoute
  '/community/bookmarks': typeof CommunityBookmarksRoute
  '/community/explore': typeof CommunityExploreRoute
  '/course/$slug': typeof CourseSlugRoute
  '/friends/activity': typeof FriendsActivityRoute
  '/game/$id': typeof GameIdRouteWithChildren
  '/news/$slug': typeof NewsSlugRoute
  '/play/friend': typeof PlayFriendRoute
  '/play/history': typeof PlayHistoryRoute
  '/play/local': typeof PlayLocalRoute
  '/puzzles/rush': typeof PuzzlesRushRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/tournament/$id': typeof TournamentIdRoute
  '/u/$username': typeof UUsernameRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/wallet/bank': typeof WalletBankRoute
  '/watch/$id': typeof WatchIdRoute
  '/admin/': typeof AdminIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/clans/': typeof ClansIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/course/': typeof CourseIndexRoute
  '/news/': typeof NewsIndexRoute
  '/play/': typeof PlayIndexRoute
  '/puzzles/': typeof PuzzlesIndexRoute
  '/room/': typeof RoomIndexRoute
  '/watch/': typeof WatchIndexRoute
  '/chat/dm/$username': typeof ChatDmUsernameRoute
  '/chat/room/$slug': typeof ChatRoomSlugRoute
  '/community/post/$id': typeof CommunityPostIdRoute
  '/game/$id/review': typeof GameIdReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-chess': typeof AboutChessRoute
  '/analysis': typeof AnalysisRoute
  '/auth': typeof AuthRoute
  '/clan': typeof ClanRouteWithChildren
  '/clubs': typeof ClubsRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/community-policy': typeof CommunityPolicyRoute
  '/contact-grievance-policy': typeof ContactGrievancePolicyRoute
  '/create-password': typeof CreatePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/editorial-team': typeof EditorialTeamRoute
  '/events': typeof EventsRoute
  '/fair-play-anti-cheating-policy': typeof FairPlayAntiCheatingPolicyRoute
  '/fair-play-policy': typeof FairPlayPolicyRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/friends': typeof FriendsRoute
  '/grievance-policy': typeof GrievancePolicyRoute
  '/home': typeof HomeRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/openings': typeof OpeningsRoute
  '/policies': typeof PoliciesRoute
  '/premium': typeof PremiumRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/rankings': typeof RankingsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/report': typeof ReportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/seasons': typeof SeasonsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/tournament': typeof TournamentRouteWithChildren
  '/tournaments': typeof TournamentsRoute
  '/verify-reset-otp': typeof VerifyResetOtpRoute
  '/wallet': typeof WalletRouteWithChildren
  '/withdrawal-policy': typeof WithdrawalPolicyRoute
  '/admin/about-chess': typeof AdminAboutChessRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/anticheat': typeof AdminAnticheatRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/clans': typeof AdminClansRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/premium': typeof AdminPremiumRoute
  '/admin/puzzles': typeof AdminPuzzlesRoute
  '/admin/ranking': typeof AdminRankingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/seasons': typeof AdminSeasonsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/admin/tr': typeof AdminTrRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/arena/$id': typeof ArenaIdRoute
  '/chat/discover': typeof ChatDiscoverRoute
  '/chat/global': typeof ChatGlobalRoute
  '/clan/$slug': typeof ClanSlugRoute
  '/community/bookmarks': typeof CommunityBookmarksRoute
  '/community/explore': typeof CommunityExploreRoute
  '/course/$slug': typeof CourseSlugRoute
  '/friends/activity': typeof FriendsActivityRoute
  '/game/$id': typeof GameIdRouteWithChildren
  '/news/$slug': typeof NewsSlugRoute
  '/play/friend': typeof PlayFriendRoute
  '/play/history': typeof PlayHistoryRoute
  '/play/local': typeof PlayLocalRoute
  '/puzzles/rush': typeof PuzzlesRushRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/tournament/$id': typeof TournamentIdRoute
  '/u/$username': typeof UUsernameRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/wallet/bank': typeof WalletBankRoute
  '/watch/$id': typeof WatchIdRoute
  '/admin': typeof AdminIndexRoute
  '/chat': typeof ChatIndexRoute
  '/clans': typeof ClansIndexRoute
  '/community': typeof CommunityIndexRoute
  '/course': typeof CourseIndexRoute
  '/news': typeof NewsIndexRoute
  '/play': typeof PlayIndexRoute
  '/puzzles': typeof PuzzlesIndexRoute
  '/room': typeof RoomIndexRoute
  '/watch': typeof WatchIndexRoute
  '/chat/dm/$username': typeof ChatDmUsernameRoute
  '/chat/room/$slug': typeof ChatRoomSlugRoute
  '/community/post/$id': typeof CommunityPostIdRoute
  '/game/$id/review': typeof GameIdReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-chess': typeof AboutChessRoute
  '/analysis': typeof AnalysisRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRouteWithChildren
  '/clan': typeof ClanRouteWithChildren
  '/clubs': typeof ClubsRoute
  '/community': typeof CommunityRouteWithChildren
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/community-policy': typeof CommunityPolicyRoute
  '/contact-grievance-policy': typeof ContactGrievancePolicyRoute
  '/create-password': typeof CreatePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/editorial-team': typeof EditorialTeamRoute
  '/events': typeof EventsRoute
  '/fair-play-anti-cheating-policy': typeof FairPlayAntiCheatingPolicyRoute
  '/fair-play-policy': typeof FairPlayPolicyRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/friends': typeof FriendsRoute
  '/grievance-policy': typeof GrievancePolicyRoute
  '/home': typeof HomeRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/openings': typeof OpeningsRoute
  '/play': typeof PlayRouteWithChildren
  '/policies': typeof PoliciesRoute
  '/premium': typeof PremiumRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/puzzles': typeof PuzzlesRouteWithChildren
  '/rankings': typeof RankingsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/report': typeof ReportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/room': typeof RoomRouteWithChildren
  '/search': typeof SearchRoute
  '/seasons': typeof SeasonsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/tournament': typeof TournamentRouteWithChildren
  '/tournaments': typeof TournamentsRoute
  '/verify-reset-otp': typeof VerifyResetOtpRoute
  '/wallet': typeof WalletRouteWithChildren
  '/withdrawal-policy': typeof WithdrawalPolicyRoute
  '/admin/about-chess': typeof AdminAboutChessRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/anticheat': typeof AdminAnticheatRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/clans': typeof AdminClansRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/policies': typeof AdminPoliciesRoute
  '/admin/premium': typeof AdminPremiumRoute
  '/admin/puzzles': typeof AdminPuzzlesRoute
  '/admin/ranking': typeof AdminRankingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/seasons': typeof AdminSeasonsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/admin/tr': typeof AdminTrRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallet': typeof AdminWalletRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/arena/$id': typeof ArenaIdRoute
  '/chat/discover': typeof ChatDiscoverRoute
  '/chat/global': typeof ChatGlobalRoute
  '/clan/$slug': typeof ClanSlugRoute
  '/community/bookmarks': typeof CommunityBookmarksRoute
  '/community/explore': typeof CommunityExploreRoute
  '/course/$slug': typeof CourseSlugRoute
  '/friends_/activity': typeof FriendsActivityRoute
  '/game/$id': typeof GameIdRouteWithChildren
  '/news/$slug': typeof NewsSlugRoute
  '/play/friend': typeof PlayFriendRoute
  '/play/history': typeof PlayHistoryRoute
  '/play/local': typeof PlayLocalRoute
  '/puzzles/rush': typeof PuzzlesRushRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/tournament/$id': typeof TournamentIdRoute
  '/u/$username': typeof UUsernameRoute
  '/verify-email/$token': typeof VerifyEmailTokenRoute
  '/wallet/bank': typeof WalletBankRoute
  '/watch/$id': typeof WatchIdRoute
  '/admin/': typeof AdminIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/clans/': typeof ClansIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/course/': typeof CourseIndexRoute
  '/news/': typeof NewsIndexRoute
  '/play/': typeof PlayIndexRoute
  '/puzzles/': typeof PuzzlesIndexRoute
  '/room/': typeof RoomIndexRoute
  '/watch/': typeof WatchIndexRoute
  '/chat/dm/$username': typeof ChatDmUsernameRoute
  '/chat/room/$slug': typeof ChatRoomSlugRoute
  '/community/post/$id': typeof CommunityPostIdRoute
  '/game/$id/review': typeof GameIdReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/about-chess'
    | '/analysis'
    | '/auth'
    | '/chat'
    | '/clan'
    | '/clubs'
    | '/community'
    | '/community-guidelines'
    | '/community-policy'
    | '/contact-grievance-policy'
    | '/create-password'
    | '/dashboard'
    | '/editorial-team'
    | '/events'
    | '/fair-play-anti-cheating-policy'
    | '/fair-play-policy'
    | '/feedback'
    | '/forgot-password'
    | '/friends'
    | '/grievance-policy'
    | '/home'
    | '/learn'
    | '/login'
    | '/news'
    | '/notifications'
    | '/onboarding'
    | '/openings'
    | '/play'
    | '/policies'
    | '/premium'
    | '/privacy-policy'
    | '/profile'
    | '/puzzles'
    | '/rankings'
    | '/refund-policy'
    | '/report'
    | '/reset-password'
    | '/room'
    | '/search'
    | '/seasons'
    | '/settings'
    | '/signup'
    | '/terms-and-conditions'
    | '/tournament'
    | '/tournaments'
    | '/verify-reset-otp'
    | '/wallet'
    | '/withdrawal-policy'
    | '/admin/about-chess'
    | '/admin/analytics'
    | '/admin/anticheat'
    | '/admin/chat'
    | '/admin/clans'
    | '/admin/community'
    | '/admin/feedback'
    | '/admin/kyc'
    | '/admin/logs'
    | '/admin/policies'
    | '/admin/premium'
    | '/admin/puzzles'
    | '/admin/ranking'
    | '/admin/reports'
    | '/admin/seasons'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/tournaments'
    | '/admin/tr'
    | '/admin/users'
    | '/admin/wallet'
    | '/admin/withdrawals'
    | '/arena/$id'
    | '/chat/discover'
    | '/chat/global'
    | '/clan/$slug'
    | '/community/bookmarks'
    | '/community/explore'
    | '/course/$slug'
    | '/friends/activity'
    | '/game/$id'
    | '/news/$slug'
    | '/play/friend'
    | '/play/history'
    | '/play/local'
    | '/puzzles/rush'
    | '/room/$roomId'
    | '/tournament/$id'
    | '/u/$username'
    | '/verify-email/$token'
    | '/wallet/bank'
    | '/watch/$id'
    | '/admin/'
    | '/chat/'
    | '/clans/'
    | '/community/'
    | '/course/'
    | '/news/'
    | '/play/'
    | '/puzzles/'
    | '/room/'
    | '/watch/'
    | '/chat/dm/$username'
    | '/chat/room/$slug'
    | '/community/post/$id'
    | '/game/$id/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about-chess'
    | '/analysis'
    | '/auth'
    | '/clan'
    | '/clubs'
    | '/community-guidelines'
    | '/community-policy'
    | '/contact-grievance-policy'
    | '/create-password'
    | '/dashboard'
    | '/editorial-team'
    | '/events'
    | '/fair-play-anti-cheating-policy'
    | '/fair-play-policy'
    | '/feedback'
    | '/forgot-password'
    | '/friends'
    | '/grievance-policy'
    | '/home'
    | '/learn'
    | '/login'
    | '/notifications'
    | '/onboarding'
    | '/openings'
    | '/policies'
    | '/premium'
    | '/privacy-policy'
    | '/profile'
    | '/rankings'
    | '/refund-policy'
    | '/report'
    | '/reset-password'
    | '/search'
    | '/seasons'
    | '/settings'
    | '/signup'
    | '/terms-and-conditions'
    | '/tournament'
    | '/tournaments'
    | '/verify-reset-otp'
    | '/wallet'
    | '/withdrawal-policy'
    | '/admin/about-chess'
    | '/admin/analytics'
    | '/admin/anticheat'
    | '/admin/chat'
    | '/admin/clans'
    | '/admin/community'
    | '/admin/feedback'
    | '/admin/kyc'
    | '/admin/logs'
    | '/admin/policies'
    | '/admin/premium'
    | '/admin/puzzles'
    | '/admin/ranking'
    | '/admin/reports'
    | '/admin/seasons'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/tournaments'
    | '/admin/tr'
    | '/admin/users'
    | '/admin/wallet'
    | '/admin/withdrawals'
    | '/arena/$id'
    | '/chat/discover'
    | '/chat/global'
    | '/clan/$slug'
    | '/community/bookmarks'
    | '/community/explore'
    | '/course/$slug'
    | '/friends/activity'
    | '/game/$id'
    | '/news/$slug'
    | '/play/friend'
    | '/play/history'
    | '/play/local'
    | '/puzzles/rush'
    | '/room/$roomId'
    | '/tournament/$id'
    | '/u/$username'
    | '/verify-email/$token'
    | '/wallet/bank'
    | '/watch/$id'
    | '/admin'
    | '/chat'
    | '/clans'
    | '/community'
    | '/course'
    | '/news'
    | '/play'
    | '/puzzles'
    | '/room'
    | '/watch'
    | '/chat/dm/$username'
    | '/chat/room/$slug'
    | '/community/post/$id'
    | '/game/$id/review'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/about-chess'
    | '/analysis'
    | '/auth'
    | '/chat'
    | '/clan'
    | '/clubs'
    | '/community'
    | '/community-guidelines'
    | '/community-policy'
    | '/contact-grievance-policy'
    | '/create-password'
    | '/dashboard'
    | '/editorial-team'
    | '/events'
    | '/fair-play-anti-cheating-policy'
    | '/fair-play-policy'
    | '/feedback'
    | '/forgot-password'
    | '/friends'
    | '/grievance-policy'
    | '/home'
    | '/learn'
    | '/login'
    | '/news'
    | '/notifications'
    | '/onboarding'
    | '/openings'
    | '/play'
    | '/policies'
    | '/premium'
    | '/privacy-policy'
    | '/profile'
    | '/puzzles'
    | '/rankings'
    | '/refund-policy'
    | '/report'
    | '/reset-password'
    | '/room'
    | '/search'
    | '/seasons'
    | '/settings'
    | '/signup'
    | '/terms-and-conditions'
    | '/tournament'
    | '/tournaments'
    | '/verify-reset-otp'
    | '/wallet'
    | '/withdrawal-policy'
    | '/admin/about-chess'
    | '/admin/analytics'
    | '/admin/anticheat'
    | '/admin/chat'
    | '/admin/clans'
    | '/admin/community'
    | '/admin/feedback'
    | '/admin/kyc'
    | '/admin/logs'
    | '/admin/policies'
    | '/admin/premium'
    | '/admin/puzzles'
    | '/admin/ranking'
    | '/admin/reports'
    | '/admin/seasons'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/tournaments'
    | '/admin/tr'
    | '/admin/users'
    | '/admin/wallet'
    | '/admin/withdrawals'
    | '/arena/$id'
    | '/chat/discover'
    | '/chat/global'
    | '/clan/$slug'
    | '/community/bookmarks'
    | '/community/explore'
    | '/course/$slug'
    | '/friends_/activity'
    | '/game/$id'
    | '/news/$slug'
    | '/play/friend'
    | '/play/history'
    | '/play/local'
    | '/puzzles/rush'
    | '/room/$roomId'
    | '/tournament/$id'
    | '/u/$username'
    | '/verify-email/$token'
    | '/wallet/bank'
    | '/watch/$id'
    | '/admin/'
    | '/chat/'
    | '/clans/'
    | '/community/'
    | '/course/'
    | '/news/'
    | '/play/'
    | '/puzzles/'
    | '/room/'
    | '/watch/'
    | '/chat/dm/$username'
    | '/chat/room/$slug'
    | '/community/post/$id'
    | '/game/$id/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AboutChessRoute: typeof AboutChessRoute
  AnalysisRoute: typeof AnalysisRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRouteWithChildren
  ClanRoute: typeof ClanRouteWithChildren
  ClubsRoute: typeof ClubsRoute
  CommunityRoute: typeof CommunityRouteWithChildren
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  CommunityPolicyRoute: typeof CommunityPolicyRoute
  ContactGrievancePolicyRoute: typeof ContactGrievancePolicyRoute
  CreatePasswordRoute: typeof CreatePasswordRoute
  DashboardRoute: typeof DashboardRoute
  EditorialTeamRoute: typeof EditorialTeamRoute
  EventsRoute: typeof EventsRoute
  FairPlayAntiCheatingPolicyRoute: typeof FairPlayAntiCheatingPolicyRoute
  FairPlayPolicyRoute: typeof FairPlayPolicyRoute
  FeedbackRoute: typeof FeedbackRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FriendsRoute: typeof FriendsRoute
  GrievancePolicyRoute: typeof GrievancePolicyRoute
  HomeRoute: typeof HomeRoute
  LearnRoute: typeof LearnRoute
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  OpeningsRoute: typeof OpeningsRoute
  PlayRoute: typeof PlayRouteWithChildren
  PoliciesRoute: typeof PoliciesRoute
  PremiumRoute: typeof PremiumRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfileRoute: typeof ProfileRoute
  PuzzlesRoute: typeof PuzzlesRouteWithChildren
  RankingsRoute: typeof RankingsRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ReportRoute: typeof ReportRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoomRoute: typeof RoomRouteWithChildren
  SearchRoute: typeof SearchRoute
  SeasonsRoute: typeof SeasonsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TournamentRoute: typeof TournamentRouteWithChildren
  TournamentsRoute: typeof TournamentsRoute
  VerifyResetOtpRoute: typeof VerifyResetOtpRoute
  WalletRoute: typeof WalletRouteWithChildren
  WithdrawalPolicyRoute: typeof WithdrawalPolicyRoute
  AdminAboutChessRoute: typeof AdminAboutChessRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAnticheatRoute: typeof AdminAnticheatRoute
  AdminChatRoute: typeof AdminChatRoute
  AdminClansRoute: typeof AdminClansRoute
  AdminCommunityRoute: typeof AdminCommunityRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminKycRoute: typeof AdminKycRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminPoliciesRoute: typeof AdminPoliciesRoute
  AdminPremiumRoute: typeof AdminPremiumRoute
  AdminPuzzlesRoute: typeof AdminPuzzlesRoute
  AdminRankingRoute: typeof AdminRankingRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSeasonsRoute: typeof AdminSeasonsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTournamentsRoute: typeof AdminTournamentsRoute
  AdminTrRoute: typeof AdminTrRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWalletRoute: typeof AdminWalletRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  ArenaIdRoute: typeof ArenaIdRoute
  CourseSlugRoute: typeof CourseSlugRoute
  FriendsActivityRoute: typeof FriendsActivityRoute
  GameIdRoute: typeof GameIdRouteWithChildren
  UUsernameRoute: typeof UUsernameRoute
  VerifyEmailTokenRoute: typeof VerifyEmailTokenRoute
  WatchIdRoute: typeof WatchIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ClansIndexRoute: typeof ClansIndexRoute
  CourseIndexRoute: typeof CourseIndexRoute
  WatchIndexRoute: typeof WatchIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdrawal-policy': {
      id: '/withdrawal-policy'
      path: '/withdrawal-policy'
      fullPath: '/withdrawal-policy'
      preLoaderRoute: typeof WithdrawalPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-reset-otp': {
      id: '/verify-reset-otp'
      path: '/verify-reset-otp'
      fullPath: '/verify-reset-otp'
      preLoaderRoute: typeof VerifyResetOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament': {
      id: '/tournament'
      path: '/tournament'
      fullPath: '/tournament'
      preLoaderRoute: typeof TournamentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons': {
      id: '/seasons'
      path: '/seasons'
      fullPath: '/seasons'
      preLoaderRoute: typeof SeasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room': {
      id: '/room'
      path: '/room'
      fullPath: '/room'
      preLoaderRoute: typeof RoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles': {
      id: '/puzzles'
      path: '/puzzles'
      fullPath: '/puzzles'
      preLoaderRoute: typeof PuzzlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openings': {
      id: '/openings'
      path: '/openings'
      fullPath: '/openings'
      preLoaderRoute: typeof OpeningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grievance-policy': {
      id: '/grievance-policy'
      path: '/grievance-policy'
      fullPath: '/grievance-policy'
      preLoaderRoute: typeof GrievancePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fair-play-policy': {
      id: '/fair-play-policy'
      path: '/fair-play-policy'
      fullPath: '/fair-play-policy'
      preLoaderRoute: typeof FairPlayPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fair-play-anti-cheating-policy': {
      id: '/fair-play-anti-cheating-policy'
      path: '/fair-play-anti-cheating-policy'
      fullPath: '/fair-play-anti-cheating-policy'
      preLoaderRoute: typeof FairPlayAntiCheatingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-team': {
      id: '/editorial-team'
      path: '/editorial-team'
      fullPath: '/editorial-team'
      preLoaderRoute: typeof EditorialTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-password': {
      id: '/create-password'
      path: '/create-password'
      fullPath: '/create-password'
      preLoaderRoute: typeof CreatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-grievance-policy': {
      id: '/contact-grievance-policy'
      path: '/contact-grievance-policy'
      fullPath: '/contact-grievance-policy'
      preLoaderRoute: typeof ContactGrievancePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-policy': {
      id: '/community-policy'
      path: '/community-policy'
      fullPath: '/community-policy'
      preLoaderRoute: typeof CommunityPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs': {
      id: '/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof ClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clan': {
      id: '/clan'
      path: '/clan'
      fullPath: '/clan'
      preLoaderRoute: typeof ClanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-chess': {
      id: '/about-chess'
      path: '/about-chess'
      fullPath: '/about-chess'
      preLoaderRoute: typeof AboutChessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/': {
      id: '/watch/'
      path: '/watch'
      fullPath: '/watch/'
      preLoaderRoute: typeof WatchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/': {
      id: '/room/'
      path: '/'
      fullPath: '/room/'
      preLoaderRoute: typeof RoomIndexRouteImport
      parentRoute: typeof RoomRoute
    }
    '/puzzles/': {
      id: '/puzzles/'
      path: '/'
      fullPath: '/puzzles/'
      preLoaderRoute: typeof PuzzlesIndexRouteImport
      parentRoute: typeof PuzzlesRoute
    }
    '/play/': {
      id: '/play/'
      path: '/'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof PlayRoute
    }
    '/news/': {
      id: '/news/'
      path: '/'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof NewsRoute
    }
    '/course/': {
      id: '/course/'
      path: '/course'
      fullPath: '/course/'
      preLoaderRoute: typeof CourseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/clans/': {
      id: '/clans/'
      path: '/clans'
      fullPath: '/clans/'
      preLoaderRoute: typeof ClansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/bank': {
      id: '/wallet/bank'
      path: '/bank'
      fullPath: '/wallet/bank'
      preLoaderRoute: typeof WalletBankRouteImport
      parentRoute: typeof WalletRoute
    }
    '/verify-email/$token': {
      id: '/verify-email/$token'
      path: '/verify-email/$token'
      fullPath: '/verify-email/$token'
      preLoaderRoute: typeof VerifyEmailTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament/$id': {
      id: '/tournament/$id'
      path: '/$id'
      fullPath: '/tournament/$id'
      preLoaderRoute: typeof TournamentIdRouteImport
      parentRoute: typeof TournamentRoute
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof RoomRoute
    }
    '/puzzles/rush': {
      id: '/puzzles/rush'
      path: '/rush'
      fullPath: '/puzzles/rush'
      preLoaderRoute: typeof PuzzlesRushRouteImport
      parentRoute: typeof PuzzlesRoute
    }
    '/play/local': {
      id: '/play/local'
      path: '/local'
      fullPath: '/play/local'
      preLoaderRoute: typeof PlayLocalRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/history': {
      id: '/play/history'
      path: '/history'
      fullPath: '/play/history'
      preLoaderRoute: typeof PlayHistoryRouteImport
      parentRoute: typeof PlayRoute
    }
    '/play/friend': {
      id: '/play/friend'
      path: '/friend'
      fullPath: '/play/friend'
      preLoaderRoute: typeof PlayFriendRouteImport
      parentRoute: typeof PlayRoute
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof NewsRoute
    }
    '/game/$id': {
      id: '/game/$id'
      path: '/game/$id'
      fullPath: '/game/$id'
      preLoaderRoute: typeof GameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends_/activity': {
      id: '/friends_/activity'
      path: '/friends/activity'
      fullPath: '/friends/activity'
      preLoaderRoute: typeof FriendsActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$slug': {
      id: '/course/$slug'
      path: '/course/$slug'
      fullPath: '/course/$slug'
      preLoaderRoute: typeof CourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/explore': {
      id: '/community/explore'
      path: '/explore'
      fullPath: '/community/explore'
      preLoaderRoute: typeof CommunityExploreRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/bookmarks': {
      id: '/community/bookmarks'
      path: '/bookmarks'
      fullPath: '/community/bookmarks'
      preLoaderRoute: typeof CommunityBookmarksRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/clan/$slug': {
      id: '/clan/$slug'
      path: '/$slug'
      fullPath: '/clan/$slug'
      preLoaderRoute: typeof ClanSlugRouteImport
      parentRoute: typeof ClanRoute
    }
    '/chat/global': {
      id: '/chat/global'
      path: '/global'
      fullPath: '/chat/global'
      preLoaderRoute: typeof ChatGlobalRouteImport
      parentRoute: typeof ChatRoute
    }
    '/chat/discover': {
      id: '/chat/discover'
      path: '/discover'
      fullPath: '/chat/discover'
      preLoaderRoute: typeof ChatDiscoverRouteImport
      parentRoute: typeof ChatRoute
    }
    '/arena/$id': {
      id: '/arena/$id'
      path: '/arena/$id'
      fullPath: '/arena/$id'
      preLoaderRoute: typeof ArenaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/admin/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/wallet': {
      id: '/admin/wallet'
      path: '/admin/wallet'
      fullPath: '/admin/wallet'
      preLoaderRoute: typeof AdminWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tr': {
      id: '/admin/tr'
      path: '/admin/tr'
      fullPath: '/admin/tr'
      preLoaderRoute: typeof AdminTrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tournaments': {
      id: '/admin/tournaments'
      path: '/admin/tournaments'
      fullPath: '/admin/tournaments'
      preLoaderRoute: typeof AdminTournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seasons': {
      id: '/admin/seasons'
      path: '/admin/seasons'
      fullPath: '/admin/seasons'
      preLoaderRoute: typeof AdminSeasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ranking': {
      id: '/admin/ranking'
      path: '/admin/ranking'
      fullPath: '/admin/ranking'
      preLoaderRoute: typeof AdminRankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/puzzles': {
      id: '/admin/puzzles'
      path: '/admin/puzzles'
      fullPath: '/admin/puzzles'
      preLoaderRoute: typeof AdminPuzzlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/premium': {
      id: '/admin/premium'
      path: '/admin/premium'
      fullPath: '/admin/premium'
      preLoaderRoute: typeof AdminPremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/policies': {
      id: '/admin/policies'
      path: '/admin/policies'
      fullPath: '/admin/policies'
      preLoaderRoute: typeof AdminPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/admin/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/admin/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/community': {
      id: '/admin/community'
      path: '/admin/community'
      fullPath: '/admin/community'
      preLoaderRoute: typeof AdminCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clans': {
      id: '/admin/clans'
      path: '/admin/clans'
      fullPath: '/admin/clans'
      preLoaderRoute: typeof AdminClansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/admin/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/anticheat': {
      id: '/admin/anticheat'
      path: '/admin/anticheat'
      fullPath: '/admin/anticheat'
      preLoaderRoute: typeof AdminAnticheatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/about-chess': {
      id: '/admin/about-chess'
      path: '/admin/about-chess'
      fullPath: '/admin/about-chess'
      preLoaderRoute: typeof AdminAboutChessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$id/review': {
      id: '/game/$id/review'
      path: '/review'
      fullPath: '/game/$id/review'
      preLoaderRoute: typeof GameIdReviewRouteImport
      parentRoute: typeof GameIdRoute
    }
    '/community/post/$id': {
      id: '/community/post/$id'
      path: '/post/$id'
      fullPath: '/community/post/$id'
      preLoaderRoute: typeof CommunityPostIdRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/chat/room/$slug': {
      id: '/chat/room/$slug'
      path: '/room/$slug'
      fullPath: '/chat/room/$slug'
      preLoaderRoute: typeof ChatRoomSlugRouteImport
      parentRoute: typeof ChatRoute
    }
    '/chat/dm/$username': {
      id: '/chat/dm/$username'
      path: '/dm/$username'
      fullPath: '/chat/dm/$username'
      preLoaderRoute: typeof ChatDmUsernameRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatDiscoverRoute: typeof ChatDiscoverRoute
  ChatGlobalRoute: typeof ChatGlobalRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ChatDmUsernameRoute: typeof ChatDmUsernameRoute
  ChatRoomSlugRoute: typeof ChatRoomSlugRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatDiscoverRoute: ChatDiscoverRoute,
  ChatGlobalRoute: ChatGlobalRoute,
  ChatIndexRoute: ChatIndexRoute,
  ChatDmUsernameRoute: ChatDmUsernameRoute,
  ChatRoomSlugRoute: ChatRoomSlugRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface ClanRouteChildren {
  ClanSlugRoute: typeof ClanSlugRoute
}

const ClanRouteChildren: ClanRouteChildren = {
  ClanSlugRoute: ClanSlugRoute,
}

const ClanRouteWithChildren = ClanRoute._addFileChildren(ClanRouteChildren)

interface CommunityRouteChildren {
  CommunityBookmarksRoute: typeof CommunityBookmarksRoute
  CommunityExploreRoute: typeof CommunityExploreRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  CommunityPostIdRoute: typeof CommunityPostIdRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityBookmarksRoute: CommunityBookmarksRoute,
  CommunityExploreRoute: CommunityExploreRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  CommunityPostIdRoute: CommunityPostIdRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

interface NewsRouteChildren {
  NewsSlugRoute: typeof NewsSlugRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsSlugRoute: NewsSlugRoute,
  NewsIndexRoute: NewsIndexRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface PlayRouteChildren {
  PlayFriendRoute: typeof PlayFriendRoute
  PlayHistoryRoute: typeof PlayHistoryRoute
  PlayLocalRoute: typeof PlayLocalRoute
  PlayIndexRoute: typeof PlayIndexRoute
}

const PlayRouteChildren: PlayRouteChildren = {
  PlayFriendRoute: PlayFriendRoute,
  PlayHistoryRoute: PlayHistoryRoute,
  PlayLocalRoute: PlayLocalRoute,
  PlayIndexRoute: PlayIndexRoute,
}

const PlayRouteWithChildren = PlayRoute._addFileChildren(PlayRouteChildren)

interface PuzzlesRouteChildren {
  PuzzlesRushRoute: typeof PuzzlesRushRoute
  PuzzlesIndexRoute: typeof PuzzlesIndexRoute
}

const PuzzlesRouteChildren: PuzzlesRouteChildren = {
  PuzzlesRushRoute: PuzzlesRushRoute,
  PuzzlesIndexRoute: PuzzlesIndexRoute,
}

const PuzzlesRouteWithChildren =
  PuzzlesRoute._addFileChildren(PuzzlesRouteChildren)

interface RoomRouteChildren {
  RoomRoomIdRoute: typeof RoomRoomIdRoute
  RoomIndexRoute: typeof RoomIndexRoute
}

const RoomRouteChildren: RoomRouteChildren = {
  RoomRoomIdRoute: RoomRoomIdRoute,
  RoomIndexRoute: RoomIndexRoute,
}

const RoomRouteWithChildren = RoomRoute._addFileChildren(RoomRouteChildren)

interface TournamentRouteChildren {
  TournamentIdRoute: typeof TournamentIdRoute
}

const TournamentRouteChildren: TournamentRouteChildren = {
  TournamentIdRoute: TournamentIdRoute,
}

const TournamentRouteWithChildren = TournamentRoute._addFileChildren(
  TournamentRouteChildren,
)

interface WalletRouteChildren {
  WalletBankRoute: typeof WalletBankRoute
}

const WalletRouteChildren: WalletRouteChildren = {
  WalletBankRoute: WalletBankRoute,
}

const WalletRouteWithChildren =
  WalletRoute._addFileChildren(WalletRouteChildren)

interface GameIdRouteChildren {
  GameIdReviewRoute: typeof GameIdReviewRoute
}

const GameIdRouteChildren: GameIdRouteChildren = {
  GameIdReviewRoute: GameIdReviewRoute,
}

const GameIdRouteWithChildren =
  GameIdRoute._addFileChildren(GameIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AboutChessRoute: AboutChessRoute,
  AnalysisRoute: AnalysisRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRouteWithChildren,
  ClanRoute: ClanRouteWithChildren,
  ClubsRoute: ClubsRoute,
  CommunityRoute: CommunityRouteWithChildren,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  CommunityPolicyRoute: CommunityPolicyRoute,
  ContactGrievancePolicyRoute: ContactGrievancePolicyRoute,
  CreatePasswordRoute: CreatePasswordRoute,
  DashboardRoute: DashboardRoute,
  EditorialTeamRoute: EditorialTeamRoute,
  EventsRoute: EventsRoute,
  FairPlayAntiCheatingPolicyRoute: FairPlayAntiCheatingPolicyRoute,
  FairPlayPolicyRoute: FairPlayPolicyRoute,
  FeedbackRoute: FeedbackRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FriendsRoute: FriendsRoute,
  GrievancePolicyRoute: GrievancePolicyRoute,
  HomeRoute: HomeRoute,
  LearnRoute: LearnRoute,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  OpeningsRoute: OpeningsRoute,
  PlayRoute: PlayRouteWithChildren,
  PoliciesRoute: PoliciesRoute,
  PremiumRoute: PremiumRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfileRoute: ProfileRoute,
  PuzzlesRoute: PuzzlesRouteWithChildren,
  RankingsRoute: RankingsRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ReportRoute: ReportRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoomRoute: RoomRouteWithChildren,
  SearchRoute: SearchRoute,
  SeasonsRoute: SeasonsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TournamentRoute: TournamentRouteWithChildren,
  TournamentsRoute: TournamentsRoute,
  VerifyResetOtpRoute: VerifyResetOtpRoute,
  WalletRoute: WalletRouteWithChildren,
  WithdrawalPolicyRoute: WithdrawalPolicyRoute,
  AdminAboutChessRoute: AdminAboutChessRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAnticheatRoute: AdminAnticheatRoute,
  AdminChatRoute: AdminChatRoute,
  AdminClansRoute: AdminClansRoute,
  AdminCommunityRoute: AdminCommunityRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminKycRoute: AdminKycRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminPoliciesRoute: AdminPoliciesRoute,
  AdminPremiumRoute: AdminPremiumRoute,
  AdminPuzzlesRoute: AdminPuzzlesRoute,
  AdminRankingRoute: AdminRankingRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSeasonsRoute: AdminSeasonsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTournamentsRoute: AdminTournamentsRoute,
  AdminTrRoute: AdminTrRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWalletRoute: AdminWalletRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  ArenaIdRoute: ArenaIdRoute,
  CourseSlugRoute: CourseSlugRoute,
  FriendsActivityRoute: FriendsActivityRoute,
  GameIdRoute: GameIdRouteWithChildren,
  UUsernameRoute: UUsernameRoute,
  VerifyEmailTokenRoute: VerifyEmailTokenRoute,
  WatchIdRoute: WatchIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  ClansIndexRoute: ClansIndexRoute,
  CourseIndexRoute: CourseIndexRoute,
  WatchIndexRoute: WatchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
